### ISSUE TITLE
Add a ReadMe

### ISSUE THREAD

**Issue by ljrodriguez1** [nmorales1991/firebase-socialauth#3]
It would be nice if there is a ReadMe file with the steps to run the app and more information

**Comment by nmorales1991** [comment]
no he querido agregar un Readme  ya que este ejemplo lo hice como ejemplo para una publicación en medium, si gustas puedes leer la publicación para saber bien como funciona. Saludos

https://medium.com/@nicomorales297/reactjs-con-firebase-authentication-f74735a54e63
